def exibir_menu():
    print("\n" + "="*40)
    print("        SOLID BANK   ")
    print("="*40)
    print("[1] Cadastrar Cliente")
    print("[2] Criar Conta")
    print("[3] Depositar")
    print("[4] Sacar")
    print("[5] Extrato")
    print("[6] Listar Contas")
    print("[0] Sair")
    print("="*40)
    return input("Escolha uma opção: ")